export default [
	{
		extension: '3gp',
		decode: true,
		encode: true,
		label: 'QuickTime / MOV',
	},
	{
		extension: 'ac3',
		decode: true,
		encode: true,
		label: 'raw AC-3',
	},
	{
		extension: 'av1',
		decode: true,
		encode: true,
		label: 'AOMedia Video 1 (AV1)',
	},
	{
		extension: 'avi',
		decode: true,
		encode: true,
		label: 'Audio Video Interleaved (AVI)',
	},
	{
		extension: 'flac',
		decode: true,
		encode: true,
		label: 'raw FLAC',
	},
	{
		extension: 'gif',
		decode: true,
		encode: true,
		label: 'CompuServe Graphics Interchange Format (GIF)',
	},
	{
		extension: 'h264',
		decode: true,
		encode: true,
		label: 'raw H.264 video',
	},
	{
		extension: 'hevc',
		decode: true,
		encode: true,
		label: 'raw HEVC video',
	},
	{
		extension: 'm4a',
		decode: true,
		encode: false,
		label: 'QuickTime / MOV',
	},
	{
		extension: 'm4v',
		decode: true,
		encode: true,
		label: 'raw MPEG-4 video',
	},
	{
		extension: 'mov',
		decode: true,
		encode: true,
		label: 'QuickTime / MOV',
	},
	{
		extension: 'mp3',
		decode: true,
		encode: true,
		label: 'MP3 (MPEG audio layer 3)',
	},
	{
		extension: 'mp4',
		decode: true,
		encode: true,
		label: 'MP4 (MPEG-4 Part 14)',
	},
	{
		extension: 'mxf',
		decode: true,
		encode: true,
		label: 'Material Exchange Format (MXF)',
	},
	{
		extension: 'mkv',
		decode: true,
		encode: true,
		label: 'Matroska Video Format (MKV)',
	},
	{
		extension: 'oga',
		decode: false,
		encode: true,
		label: 'Ogg Audio',
	},
	{
		extension: 'ogg',
		decode: true,
		encode: true,
		label: 'Ogg',
	},
	{
		extension: 'ogv',
		decode: false,
		encode: true,
		label: 'Ogg Video',
	},
	{
		extension: 'opengl',
		decode: false,
		encode: true,
		label: 'OpenGL output',
	},
	{
		extension: 'opus',
		decode: true,
		encode: true,
		label: 'Opus',
	},
	{
		extension: 'ts',
		decode: true,
		encode: false,
		label: 'MPEG transport stream',
	},
	{
		extension: 'wav',
		decode: true,
		encode: true,
		label: 'WAV / WAVE (Waveform Audio)',
	},
	{
		extension: 'webm',
		decode: true,
		encode: true,
		label: 'WebM',
	},
	{
		extension: 'wma',
		decode: true,
		encode: true,
		label: 'Windows Media Audio (WMA)',
	},
	{
		extension: 'wmv',
		decode: true,
		encode: true,
		label: 'Windows Media Video (WMV)',
	},
	{
		extension: 'jpg',
		decode: true,
		encode: true,
		label: 'JPEG image',
	},
	{
		extension: 'jpeg',
		decode: true,
		encode: true,
		label: 'JPEG image',
	},
	{
		extension: 'png',
		decode: true,
		encode: true,
		label: 'Portable Network Graphics',
	},
	{
		extension: 'bmp',
		decode: true,
		encode: true,
		label: 'Bitmap image',
	},
	{
		extension: 'tiff',
		decode: true,
		encode: true,
		label: 'Tagged Image File Format',
	},
	{
		extension: 'webp',
		decode: true,
		encode: true,
		label: 'WebP image',
	},
]
