name: Lint

on: [push]

jobs:
  php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.2', '8.3']

    name: php${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Lint
        run: composer run lint || ( echo 'Please run `composer run lint` and fix your code' && exit 1 )

  php-cs-fixer:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.2', '8.3']

    name: cs php${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: composer i

      - name: Update dev dependencies
        run: composer update -n --dev

      - name: Run coding standards check
        run: composer run cs:check || ( echo 'Please run `composer run cs:fix` to format your code' && exit 1 )

  xml-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download schema
        run: wget https://apps.nextcloud.com/schema/apps/info.xsd
      - name: Lint info.xml
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./appinfo/info.xml
          xml-schema-file: ./info.xsd
